Repository birdrides/mockingbird, pull requests merged in 2019-10, with the labels that each got.

#8 Add missing change directory command to Carthage setup instructions
  README.md
Labels: documentation

#9 Fix class-only protocol initializer generation
  MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
  MockingbirdGenerator/Parser/Models/RawType.swift
  MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
  MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
  MockingbirdSupport/Swift/Misc.swift
  MockingbirdTests/Framework/InitializerTests.swift
Labels: JIRA OS-5

#10 handle non-alphanumeric target names
  Mockingbird.xcodeproj/project.pbxproj
  MockingbirdGenerator/Parser/Cache/CodableTarget.swift
  MockingbirdTests/Generator/PBXTargetTests.swift
Labels: JIRA OS-6

#14 Remove generic type alphabetization
  MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
  MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
  MockingbirdGenerator/Parser/Models/Method.swift
  MockingbirdGenerator/Parser/Models/MockableType.swift
  MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
  MockingbirdTestsHost/Generics.swift
Labels: JIRA OS-8

#15 Fix fnmatch implementation on macOS Catalina
  .github/workflows/build-framework-cli.yml
  Mockingbird.xcodeproj/project.pbxproj
  MockingbirdGenerator/Utilities/Path+Fnmatch.swift
  MockingbirdTests/Generator/PathFnmatchTests.swift
Labels: JIRA OS-9
