Repository birdrides/mockingbird, pull requests merged in 2019-11, with the labels that each got.

#16 Remove automatic binary installation from pod install prepare_command
  MockingbirdFramework.podspec
  README.md
Labels: JIRA OS-10

#17 Remove macOS Mojave CI runner
  .github/workflows/build-framework-cli.yml
Labels: JIRA OS-11

#18 Invalidate cached mocked modules when the CLI version changes
  MockingbirdCli/Interface/Generator.swift
  MockingbirdGenerator/Parser/Cache/CodableTarget.swift
  MockingbirdGenerator/Parser/Operations/CheckCacheOperation.swift
Labels: JIRA OS-12

#19 Gather module names for inherited types
  MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
Labels: JIRA OS-13

#20 Include declarations in extensions when flattening inherited types
  MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
  MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
  MockingbirdTests/E2E/ExtensionsMockableTests.swift
  MockingbirdTests/E2E/ExtensionsStubbableTests.swift
  MockingbirdTestsHost/Extensions.swift
Labels: JIRA OS-14

#21 Fix matching closures with wildcard argument matchers
  Mockingbird.xcodeproj/project.pbxproj
  MockingbirdFramework/DSL/TypeFacade.swift
  MockingbirdFramework/Mockingbird.swift
  MockingbirdFramework/Verification/Invocation.swift
  MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
  MockingbirdTests/E2E/ClosureParametersStubbableTests.swift
  MockingbirdTests/Framework/ClosureParameterTests.swift
  MockingbirdTestsHost/ClosureParameters.swift
Labels: JIRA OS-15
